### PR TITLE
Fix Battle logs

### PR DESCRIPTION
**Pull request by illiptic**
- Display battle by round
- fix reload issue (defaultHistory link error)
- Fix message rendering bug Issue #207 (I think!)

### CODE REVIEW

**Comment by seiyria** [comment]
Awesome. Can you show me a screenshot of the changes?

**Comment by illiptic** [comment]
screen shot 2017-05-29 at 10 33 20
screen shot 2017-05-29 at 10 33 24
screen shot 2017-05-29 at 10 33 51

**Comment by illiptic** [comment]
If you don't like the layout I can also isolate just the bugfixes. I should have committed them separately... stupid me.

**Comment by seiyria** [comment]
It's alright. It looks fine. Folks will adjust.

**Pull request merged**
