### PR TITLE
Replace pet carousel with list menu

### PR DESCRIPTION
**Pull request by illiptic**
Issue #198

Created a list-panel for pets, like the chat's contacts' list.
Don't know if you had that in mind.

Let me know!

### CODE REVIEW

**Comment by seiyria** [comment]
can you show me a screenshot?

**Comment by illiptic** [comment]
Sure, here are a few.

Desktop, no active pet:
screen shot 2017-05-25 at 09 07 18

Desktop, with pet:
screen shot 2017-05-25 at 09 08 02

Medium, with open menu:
screen shot 2017-05-25 at 09 08 15

Small/Mobile, with open menu:
screen shot 2017-05-25 at 09 10 12

**Comment by seiyria** [comment]
I like this, it's what I did for chat too. Can you add some padding to the
name area? It's a bit squished. I'll look at the code at that time but it's
probably fine.

**Comment by seiyria** [comment]
Thanks for the awesome contribution!

**Pull request merged**
